apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.name }}-config"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: "{{ .Values.labels.app }}"
data:
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: "{{ $value }}"
  {{- end }}