{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: "{{ .Values.labels.app }}"
spec:
  {{- if and (eq .Values.workload.type "StatefulSet") .Values.service.headless }}
  clusterIP: None
  {{- else }}
  type: {{ .Values.service.type }}
  {{- end }}
  selector:
    app: "{{ .Values.labels.app }}"
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.container.port }}
{{- end }}