name: Docker Helm Template Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      # 1. Clona tu repositorio en la m√°quina virtual
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry-1.docker.io
          username: ${{ secrets.DOCKER_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0
      - name: Login to Helm Registry
        env:
          HELM_REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "${HELM_REGISTRY_PASSWORD}" | helm registry login registry-1.docker.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Deploy files
        run: |
          sed -i "s|{{ version }}|${{ github.run_number }}|g" Chart.yaml
          cat Chart.yaml
          PKG_FILE=$(helm package . | awk '{print $NF}')
          echo "$PKG_FILE"
          helm push "$PKG_FILE" oci://registry-1.docker.io/${{ secrets.DOCKER_USERNAME }}